### ISSUE TITLE
South Sudan in the text results as South Sudan AND Sudan

### ISSUE THREAD

**Issue by R01010010R** [koheiw/newsmap#13]
When I have a text with "South Sudan" then the results are South Sudan AND Sudan.

Working example:
```
library(quanteda)
library(newsmap)

text <- "South Sudan"
toks <- tokens(text)
tokens_lookup(toks, data_dictionary_newsmap_en, levels = 3)

[1] "SS" "SD"
```

Expected behaviour:
```
[1] "SS"
```

**Comment by stefan-mueller** [comment]
`tokens_lookup()` assigns "South" to South Sudan and "Sudan" to Sudan. This is because "South Sudan" is not compounded. One solution is to use `tokens_compound()` first to compound the multiword expressions included in `data_dictionary_newsmap_en`, and to apply the dictionary to the tokens object afterwards:

```r
library(quanteda)
library(newsmap)

text <- "South Sudan is a country in Africa."

toks <- tokens(text) %>% 
    tokens_compound(data_dictionary_newsmap_en)

toks
# tokens from 1 document.
# text1 :
#     [1] "South_Sudan" "is"          "a"           "country"     "in"          "Africa"     
# [7] "." 

tokens_lookup(toks, data_dictionary_newsmap_en, levels = 3)
# tokens from 1 document.
# text1 :
#     [1] "SS"
```

**Comment by R01010010R** [comment]
Thanks for pointing out this very simple solution Stefan! True, I didn't think of using the dictionary as a pattern. Good point!

Maybe a hint in the README could help for others? Because people don't know upfront if in data such as _ yahoo-news_ South Sudan appears.

**Comment by R01010010R** [comment]
I just realized there are even other instances in my data.

For example, **Papua New Guinea**:
```
[1] "PG" "GN"
```

And, **Turks and Caicos Islands**:
```
[1] "TC" "TR"
```

Haven't check all countries, but these were the ones that I found in my data.

Compounded tokens work for Papua New Guinea, but not for Turks and Caicos Islands because of `Turk*` in https://github.com/koheiw/newsmap/blob/master/dict/english.yml#L195

**Comment by R01010010R** [comment]
I just extracted the level 3 part of https://github.com/koheiw/newsmap/blob/master/dict/english.yml, removed the `*` and then checked which ones result in more than one ISO code even when using compound. Here is the list:

```
text <- c(
    'Turks and Caicos Islands',
    'Turks and Caicos Island',
    'British Virgin Islands',
    'French Guiana',
    'French Guianese',
    'Turkmenistan',
    'Turkmen',
    'Cook Islands',
    'Cook Island',
    'Avarua',
    'American Samoa',
    'American Samoan',
    'Cook Islands',
    'Cook Island',
    'Avarua',
    'French Polynesia',
    'French Polynesian'
)

corp <- corpus(text)
toks <- tokens(corp) %>% 
    tokens_compound(data_dictionary_newsmap_en)

tokens_lookup(toks, data_dictionary_newsmap_en, levels = 3)

tokens from 17 documents.
text1 :
[1] "TC" "TR"

text2 :
[1] "TC" "TR"

text3 :
[1] "VG" "GB"

text4 :
[1] "GF" "FR"

text5 :
[1] "GF" "FR"

text6 :
[1] "TM" "TR"

text7 :
[1] "TM" "TR"

text8 :
[1] "CC" "CK"

text9 :
[1] "CC" "CK"

text10 :
[1] "CC" "CK"

text11 :
[1] "US" "AS"

text12 :
[1] "US" "AS"

text13 :
[1] "CC" "CK"

text14 :
[1] "CC" "CK"

text15 :
[1] "CC" "CK"

text16 :
[1] "FR" "PF"

text17 :
[1] "FR" "PF"
```

**Comment by koheiw** [comment]
These are not because of a bug (e.g. "French Polynesian" contains "French") but the deeper problem of geographical ambiguity. I am not worried too much about these false positives because documents (news stories in my case) about these small countries are rare, but your use case might be different.

If you want to discuss this issue further please mention this in https://github.com/quanteda/quanteda/issues. We could add option to ignore nested (overlapped) elements to `tokens_lookup()`.
